#!/usr/bin/env bash

# Path to the passwd file
passwd_file="/etc/passwd"

# Use while loop to read the file line by line
while IFS=: read -r username _ userid _ _ home_dir _
do
  # Display the required information
  echo "Username: $username"
  echo "User ID: $userid"
  echo "Home Directory: $home_dir"
done < "$passwd_file"

