#!/usr/bin/env bash
# Initialize a counter
counter=1

# Use while loop to iterate from 1 to 10
while [ $counter -le 10 ]
do
  # Check for specific iterations and display messages accordingly
  if [ $counter -eq 4 ]
  then
    echo "bad luck"
  elif [ $counter -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi

  ((counter++))
done
