#!/usr/bin/env bash
#Display Besst School 10 times  Initialize a counter
i=1
while [ "$i" -le 10 ]
do
  # Check for specific iterations and display messages accordingly
  if [ "$i" -eq 4 ]
  then
	  echo "bad luck"
  elif [ "$i" -eq 8 ]
  then
	  echo "good luck"
  else
	  echo "Best School"
  fi
  i=$(( i + 1 ))
done
