#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes
hours=0
minutes=1

# Use while loop to display time for 12 hours and 59 minutes
while [ $hours -le 12 ]
do
  # Display hours and minutes
  echo "$hours:$minutes"

  # Increment minutes
  ((minutes++))

  # Check and reset minutes and increment hours if necessary
  if [ $minutes -gt 59 ]; then
    minutes=1
    ((hours++))
  fi
done | head -n 70
