#!/usr/bin/env bash
#scrit that search school file
FILE="school"
if [ -e $file ]
then
  echo "$FILE school file exists"

  if [ -s $FILE ]
  then
	  echo "$FILE file is not empty"
  else
	  echo "$FILE file is empty"
  fi
  
  if [ -f $FILE ]
  then
	  echo "$FILE is a regular file"
  fi
else
	echo "$FILE file does not exist"
fi

