#!/bin/bash

# Set Nginx user in configuration
sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf

# Update Nginx to listen on all active IPs on port 8080
sed -i 's/^listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart

